"""init migration

Revision ID: 435ce525be50
Revises: None
Create Date: 2016-11-02 21:11:28.024000

"""

# revision identifiers, used by Alembic.
revision = '435ce525be50'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    ### end Alembic commands ###
